---
version: "3.1"
services:
  sonarr:
    image: crowsbyte/librespot
    container_name: librespot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/snapfifo:/data
    ports:
      - 8989:8989
    restart: unless-stopped
