Version: '3.8'

services:
  librespot:
    build: 
      context: .
      dockerfile: Dockerfile.pi
    container_name: librespot-mini
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      - TZ=America/New_York
#      - SNAPCLIENT_SOUNDCARD=sysdefault
 #     - HOSTID=Trying
  #    - SNAPCLIENT_HOST=192.168.1.198
   #   - CLIENTNAME="Desktop Trial" 
 #     - PULSE_SERVER=unix:/run/user/1000/pulse/native
 #     - PULSE_SINK=snapcast


