name: Build Develop Image

on:
  push:
    branches: [ "green" ]
  pull_request:
    branches: [ "green" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crowsbyte/librespot:green
